using System.Collections;
using System.Collections.Generic;
using Ktyl.Util;
using UnityEngine;

public class Artefact : ScriptableObject
{

    public int artefactID => _artefactID;
    [SerializeField] private int _artefactID;
    public string dialogueKey => _dialogueKey;
    [SerializeField] private string _dialogueKey;
    
    public string descriptionKey => _descriptionKey;
    [SerializeField] private string _descriptionKey;

    public string Name => _name;
    [SerializeField] private string _name;
    
    public GameObject Prefab => _prefab;
    [SerializeField] private GameObject _prefab;

    public GameEvent OnFound => _onFound;
    [SerializeField] private GameEvent _onFound;
    
    public bool show => _show;
    private bool _show = false;
    public bool canInteract => _canInteract;
    private bool _canInteract = false;

    public virtual void Pickup()
    {
    }
}