using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

[CreateAssetMenu(menuName = "KernelPanic/Rendering/Glitch Render Pipeline Asset")]
public class GlitchRenderPipelineAsset : RenderPipelineAsset
{
    [System.Serializable]
    public class Settings
    {
        public ForwardRenderer forwardRenderer;
    }
    public Settings settings;
    
    protected override RenderPipeline CreatePipeline()
    {
        return new GlitchRenderPipelineInstance();
    }
}
