using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Artefact : ScriptableObject
{

    public int artefactID => _artefactID;
    [SerializeField] private int _artefactID;
    public string dialogueKey => _dialogueKey;
    [SerializeField] private string _dialogueKey;

    public string Name => _name;
    [SerializeField] private string _name;
    
    public GameObject Prefab => _prefab;
    [SerializeField] private GameObject _prefab;

    public bool show => _show;
    private bool _show = false;
    public bool canInteract => _canInteract;
    private bool _canInteract = false;

    public virtual void Pickup()
    {
    }
}