using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class GlitchRenderPipelineInstance : RenderPipeline
{
    private readonly CameraRenderer _renderer = new CameraRenderer();
    private ForwardRenderer _forwardRenderer;

    public GlitchRenderPipelineInstance()
    {
    }
    
    protected override void Render(ScriptableRenderContext context, Camera[] cameras)
    {
        foreach (var camera in cameras)
        {
            _renderer.Render(context, camera);
        }
    }
}
